use_frameworks!

platform :ios, '9.0'

target 'HCDesignKit_Example' do
  pod 'HCDesignKit', :path => '../'

  target 'HCDesignKit_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
